apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: fix-redis-volume-ownership
  name: fix-redis-volume-ownership
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: fix-redis-volume-ownership
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name: fix-redis-volume-ownership
        image: "docker.io/bitnami/redis:latest"
        imagePullPolicy: "Always"
        env:
        - name: REDIS_REPLICATION_MODE
          value: master
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DISABLE_COMMANDS
          value:
        ports:
        - name: redis
          containerPort: 6379
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
          exec:
            command:
            - redis-cli
            - ping
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
          exec:
            command:
            - redis-cli
            - ping
        resources:
          null

        volumeMounts:
        - mountPath: /bitnami/redis/data
          name: fix-redis-volume-ownership-claim0
        - mountPath: /opt/bitnami/redis/conf/redis.conf
          name: fix-redis-volume-ownership-claim1
      restartPolicy: Always
      volumes:
      - name: fix-redis-volume-ownership-claim0
        persistentVolumeClaim:
          claimName: fix-redis-volume-ownership-claim0
      - name: fix-redis-volume-ownership-claim1
        persistentVolumeClaim:
          claimName: fix-redis-volume-ownership-claim1
status: {}
