apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
        app: apolloserver
        tier: frontend
  template:
    metadata:
      labels:
        app: apolloserver
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: radkin/apolloserver:latest
        env:
        - name: GET_HOSTS_FROM
          value: "dns"
        - name: REDIS_URL
          value: redis-follower:6379
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9000
