apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: apolloserver
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 80
  selector:
    app: apolloserver
    tier: frontend
