apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: lb
  name: lb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: lb
    spec:
      containers:
      - image: dockercloud/haproxy
        name: lb
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: lb-claim0
      restartPolicy: Always
      volumes:
      - name: lb-claim0
        persistentVolumeClaim:
          claimName: lb-claim0
status: {}
