apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: redis-master
  name: redis-master
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: redis-master
        app: master
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - web-store
            topologyKey: "kubernetes.io/hostname"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - master
            topologyKey: "kubernetes.io/hostname"
      securityContext:
        runAsUser: 0
      containers:
      - env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: REDIS_REPLICATION_MODE
          value: master
        image: bitnami/redis:latest
        name: redis-master
        ports:
        - containerPort: 6379
        resources: {}
        volumeMounts:
        - mountPath: /bitnami/redis/data
          name: redis-master-claim0
        - mountPath: /opt/bitnami/redis/conf/redis.conf
          name: redis-master-claim1
      restartPolicy: Always
      volumes:
      - name: redis-master-claim0
        persistentVolumeClaim:
          claimName: redis-master-claim0
      - name: redis-master-claim1
        persistentVolumeClaim:
          claimName: redis-master-claim1
status: {}
