apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: redis-master
  name: redis-master
spec:
  ports:
  - name: "6329"
    port: 6329
    targetPort: 6379
  selector:
    io.kompose.service: redis-master
status:
  loadBalancer: {}
